import Anthropic from "@anthropic-ai/sdk";
import { marked } from "marked";
import type { Digest, DigestSection } from "./types";

export async function generateDigest(
  apiKey: string,
  topics: string[],
  previousDigests: Digest[],
  dashboardUrl: string
): Promise<Digest> {
  const client = new Anthropic({ apiKey });
  const today = new Date().toISOString().split("T")[0];

  const previousContext =
    previousDigests.length > 0
      ? `\n\nPrevious digests (avoid repeating, track developing stories):\n${previousDigests
          .map(
            (d) =>
              `--- ${d.date} ---\n${d.sections.map((s) => `${s.title}: ${s.content.slice(0, 200)}`).join("\n")}`
          )
          .join("\n\n")}`
      : "";

  const systemPrompt = `You are a concise news digest curator. Today is ${today}. Topics: ${topics.join(", ")}.

Search the web for each topic. Write a digest with exactly 3 sections in this order:

1. **Today's Updates** - What happened today/last 24 hours (bullet points)
2. **This Week** - Notable developments from the past 7 days (bullet points)
3. **Big Picture** - Major trends across the topics (1-2 short paragraphs)

Rules:
- Be concise. Short, punchy bullet points. No filler.
- If there's no significant news for a topic or section, just say "Nothing notable today" or similar. Don't stretch or fabricate.
- Mention sources when relevant.
- Not every section needs to be long.${previousContext}

Respond with ONLY a JSON object (no markdown fences):
{
  "subject": "Brief catchy subject line",
  "sections": [
    {"title": "Today's Updates", "content": "..."},
    {"title": "This Week", "content": "..."},
    {"title": "Big Picture", "content": "..."}
  ]
}`;

  let fullText = "";
  let stopReason: string | null = null;
  let messages: Anthropic.MessageParam[] = [
    { role: "user", content: "Research and generate today's digest." },
  ];

  while (true) {
    const response = await client.messages.create({
      model: "claude-opus-4-6",
      max_tokens: 16000,
      system: systemPrompt,
      tools: [
        {
          type: "web_search_20250305",
          name: "web_search",
          max_uses: 30,
        },
      ],
      messages,
    });

    stopReason = response.stop_reason;

    for (const block of response.content) {
      if (block.type === "text") {
        fullText += block.text;
      }
    }

    if (stopReason === "pause_turn") {
      messages = [
        ...messages,
        { role: "assistant", content: response.content },
        { role: "user", content: "Please continue." },
      ];
      fullText = "";
    } else {
      break;
    }
  }

  const jsonMatch = fullText.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new Error("No JSON found in response");
  const parsed = JSON.parse(jsonMatch[0]);
  const sections: DigestSection[] = parsed.sections;
  const subject: string = parsed.subject;

  const html = renderDigestHtml(subject, sections, today, dashboardUrl);

  return { date: today, subject, sections, html };
}

function renderDigestHtml(
  subject: string,
  sections: DigestSection[],
  date: string,
  dashboardUrl: string
): string {
  const sectionHtml = sections
    .map(
      (s) => `
    <div style="margin-bottom:28px;">
      <h2 style="color:#e67e22;font-size:20px;margin:0 0 12px 0;border-bottom:2px solid #f0f0f0;padding-bottom:8px;">${escapeHtml(s.title)}</h2>
      <div style="color:#333;font-size:15px;line-height:1.7;">${markdownToHtml(s.content.trim())}</div>
    </div>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:20px;">
    <div style="background:#fff;border-radius:12px;padding:32px;box-shadow:0 2px 8px rgba(0,0,0,0.06);">
      <div style="text-align:center;margin-bottom:24px;">
        <h1 style="color:#1a1a2e;font-size:24px;margin:0 0 4px 0;">${escapeHtml(subject)}</h1>
        <p style="color:#888;font-size:13px;margin:0;">${date} &middot; news.chadnauseam.com Daily Digest</p>
      </div>
      ${sectionHtml}
      <div style="text-align:center;padding-top:20px;border-top:1px solid #f0f0f0;">
        <p style="color:#aaa;font-size:12px;margin:0;">
          <a href="${dashboardUrl}" style="color:#e67e22;text-decoration:none;">Manage digest settings</a>
          &nbsp;&middot;&nbsp;
          <a href="${dashboardUrl}" style="color:#999;text-decoration:none;">Unsubscribe</a>
        </p>
        <p style="color:#ccc;font-size:11px;margin:6px 0 0;">Generated by news.chadnauseam.com</p>
      </div>
    </div>
  </div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function markdownToHtml(text: string): string {
  return marked.parse(text, { async: false }) as string;
}
